version: 1
frontend:
  phases:
    build:
      commands:
        - echo "Building frontend-only application"
  artifacts:
    baseDirectory: frontend
    files:
      - "**/*"
  cache:
    paths: [] 